language: node_js
before_install: 
  - npm install -g npm@5.6.0
script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
  fqdn: housewarming.poiters.be